import type { RegionTag, SoilType } from "./types"

export const SOIL_TYPES: SoilType[] = [
    "Alluvial Soil",
    "Black Soil (Regur)",
    "Red & Yellow Soil",
    "Laterite Soil",
    "Desert / Arid Soil",
    "Mountain / Forest Soil",
    "Saline / Alkaline Soil",
    "Peaty / Marshy Soil",
]

export const STATES: string[] = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]

export const STATE_SOIL_MAP: Record<string, SoilType[]> = {
    "Andhra Pradesh": ["Alluvial Soil", "Black Soil (Regur)", "Red & Yellow Soil", "Saline / Alkaline Soil"],
    "Arunachal Pradesh": ["Mountain / Forest Soil", "Red & Yellow Soil"],
    "Assam": ["Alluvial Soil", "Mountain / Forest Soil", "Laterite Soil", "Peaty / Marshy Soil"],
    "Bihar": ["Alluvial Soil", "Red & Yellow Soil"],
    "Chhattisgarh": ["Red & Yellow Soil", "Black Soil (Regur)", "Alluvial Soil"],
    "Goa": ["Laterite Soil", "Red & Yellow Soil"],
    "Gujarat": ["Black Soil (Regur)", "Alluvial Soil", "Desert / Arid Soil", "Saline / Alkaline Soil"],
    "Haryana": ["Alluvial Soil", "Desert / Arid Soil", "Saline / Alkaline Soil"],
    "Himachal Pradesh": ["Mountain / Forest Soil", "Alluvial Soil"],
    "Jharkhand": ["Red & Yellow Soil", "Laterite Soil", "Alluvial Soil"],
    "Karnataka": ["Black Soil (Regur)", "Red & Yellow Soil", "Laterite Soil"],
    "Kerala": ["Laterite Soil", "Peaty / Marshy Soil", "Red & Yellow Soil"],
    "Madhya Pradesh": ["Black Soil (Regur)", "Red & Yellow Soil", "Alluvial Soil"],
    "Maharashtra": ["Black Soil (Regur)", "Laterite Soil", "Red & Yellow Soil", "Saline / Alkaline Soil"],
    "Manipur": ["Mountain / Forest Soil", "Red & Yellow Soil"],
    "Meghalaya": ["Laterite Soil", "Mountain / Forest Soil", "Red & Yellow Soil"],
    "Mizoram": ["Mountain / Forest Soil", "Red & Yellow Soil"],
    "Nagaland": ["Mountain / Forest Soil", "Red & Yellow Soil"],
    "Odisha": ["Alluvial Soil", "Red & Yellow Soil", "Laterite Soil", "Peaty / Marshy Soil"],
    "Punjab": ["Alluvial Soil", "Desert / Arid Soil", "Saline / Alkaline Soil"],
    "Rajasthan": ["Desert / Arid Soil", "Alluvial Soil", "Saline / Alkaline Soil"],
    "Sikkim": ["Mountain / Forest Soil"],
    "Tamil Nadu": ["Alluvial Soil", "Black Soil (Regur)", "Red & Yellow Soil", "Laterite Soil", "Peaty / Marshy Soil"],
    "Telangana": ["Black Soil (Regur)", "Red & Yellow Soil"],
    "Tripura": ["Mountain / Forest Soil", "Red & Yellow Soil"],
    "Uttar Pradesh": ["Alluvial Soil", "Red & Yellow Soil"],
    "Uttarakhand": ["Mountain / Forest Soil", "Alluvial Soil"],
    "West Bengal": ["Alluvial Soil", "Red & Yellow Soil", "Peaty / Marshy Soil"],
    "Andaman and Nicobar Islands": ["Laterite Soil", "Red & Yellow Soil"],
    "Chandigarh": ["Alluvial Soil"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Red & Yellow Soil", "Laterite Soil"],
    "Delhi": ["Alluvial Soil"],
    "Jammu and Kashmir": ["Mountain / Forest Soil"],
    "Ladakh": ["Mountain / Forest Soil", "Desert / Arid Soil"],
    "Lakshadweep": ["Laterite Soil", "Peaty / Marshy Soil"],
    "Puducherry": ["Alluvial Soil", "Red & Yellow Soil", "Laterite Soil"],
}

export const STATE_REGION_MAP: Record<string, RegionTag[]> = {
    "Andhra Pradesh": ["south", "coastal"],
    "Arunachal Pradesh": ["northeast", "mountain"],
    "Assam": ["northeast", "east"],
    "Bihar": ["east"],
    "Chhattisgarh": ["central", "east"],
    "Goa": ["west", "coastal"],
    "Gujarat": ["west", "desert", "coastal"],
    "Haryana": ["north", "desert"],
    "Himachal Pradesh": ["north", "mountain"],
    "Jharkhand": ["east"],
    "Karnataka": ["south", "coastal"],
    "Kerala": ["south", "coastal"],
    "Madhya Pradesh": ["central"],
    "Maharashtra": ["west", "coastal"],
    "Manipur": ["northeast", "mountain"],
    "Meghalaya": ["northeast", "mountain"],
    "Mizoram": ["northeast", "mountain"],
    "Nagaland": ["northeast", "mountain"],
    "Odisha": ["east", "coastal"],
    "Punjab": ["north", "desert"],
    "Rajasthan": ["north", "desert"],
    "Sikkim": ["northeast", "mountain"],
    "Tamil Nadu": ["south", "coastal"],
    "Telangana": ["south"],
    "Tripura": ["northeast"],
    "Uttar Pradesh": ["north"],
    "Uttarakhand": ["north", "mountain"],
    "West Bengal": ["east", "coastal"],
    "Andaman and Nicobar Islands": ["coastal"],
    "Chandigarh": ["north"],
    "Dadra and Nagar Haveli and Daman and Diu": ["west", "coastal"],
    "Delhi": ["north"],
    "Jammu and Kashmir": ["north", "mountain"],
    "Ladakh": ["north", "mountain", "desert"],
    "Lakshadweep": ["coastal"],
    "Puducherry": ["south", "coastal"],
}

const STATE_ALIASES: Record<string, string> = {
    "andhra pradesh": "Andhra Pradesh",
    "arunachal pradesh": "Arunachal Pradesh",
    assam: "Assam",
    bihar: "Bihar",
    chhattisgarh: "Chhattisgarh",
    goa: "Goa",
    gujarat: "Gujarat",
    haryana: "Haryana",
    "himachal pradesh": "Himachal Pradesh",
    jharkhand: "Jharkhand",
    karnataka: "Karnataka",
    kerala: "Kerala",
    "madhya pradesh": "Madhya Pradesh",
    maharashtra: "Maharashtra",
    manipur: "Manipur",
    meghalaya: "Meghalaya",
    mizoram: "Mizoram",
    nagaland: "Nagaland",
    odisha: "Odisha",
    orissa: "Odisha",
    punjab: "Punjab",
    rajasthan: "Rajasthan",
    sikkim: "Sikkim",
    "tamil nadu": "Tamil Nadu",
    telangana: "Telangana",
    tripura: "Tripura",
    "uttar pradesh": "Uttar Pradesh",
    uttarakhand: "Uttarakhand",
    uttaranchal: "Uttarakhand",
    "west bengal": "West Bengal",
    "andaman and nicobar islands": "Andaman and Nicobar Islands",
    chandigarh: "Chandigarh",
    "dadra and nagar haveli and daman and diu": "Dadra and Nagar Haveli and Daman and Diu",
    delhi: "Delhi",
    "national capital territory of delhi": "Delhi",
    "jammu and kashmir": "Jammu and Kashmir",
    ladakh: "Ladakh",
    lakshadweep: "Lakshadweep",
    puducherry: "Puducherry",
    pondicherry: "Puducherry",
}

export function normalizeStateName(raw: string): string | null {
    const cleaned = raw.trim().toLowerCase()
    if (STATE_ALIASES[cleaned]) return STATE_ALIASES[cleaned]
    const match = STATES.find((s) => s.toLowerCase() === cleaned)
    return match ?? null
}

export function getSoilsForState(state: string): SoilType[] {
    return STATE_SOIL_MAP[state] ?? ["Alluvial Soil"]
}

export function getDefaultSoilForState(state: string): SoilType {
    return getSoilsForState(state)[0]
}
